### ISSUE TITLE
Colour issues with missing IMD?

### ISSUE THREAD

**Issue by jacgrout** [ThomUK/imdvizzer#10]
It looks like the colours are slightly inconsistent when the ICB doesn't have all 10 IMD's? For example Surrey Heartlands ICB and Frimley ICB. In tackling the issue to expand to sub-ICBs this colour issue would become more apparent/more of an issue.

**Comment by ThomUK** [comment]
Thanks for the spot!  Not a single IMD 1 in Surrey or Frimley.

**Comment by jacgrout** [comment]
> Thanks for the spot! Not a single IMD 1 in Surrey or Frimley.

Yeah and with smaller geographies like sub-ICB then there could well be others missing too.
