### ISSUE TITLE
Example maps in the README seem squashed

### ISSUE THREAD

**Issue by francisbarton** [ThomUK/imdvizzer#4]
It looks like the projection used for the generation of the example maps in the README is off. I don't know why - the data uses EPSG 4326 and this should be handled perfectly well by `geom_sf()`.

I have tried to fix this by binding the data to the `sf` table rather than vice versa. This seems to produce maps that are properly projected.

PR #3 should close this.

**Comment by ThomUK** [comment]
closed by #3
